###
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@user.com",
  "password": "admin"
}

###
@tokenAdmin = {{ adminLogin.response.body.access_token }}

###
# @name readerLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "reader@user.com",
  "password": "reader"
}

###
@tokenReader = {{ readerLogin.response.body.access_token }}

### Create Admin
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@user.com",
  "password": "admin",
  "role": "ADMIN"
}

### Create Reader
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
  "name": "Reader",
  "email": "reader@user.com",
  "password": "reader",
  "role": "READER"
}

###
GET http://localhost:3000/users
Authorization: Bearer {{tokenAdmin}}

###
GET http://localhost:3000/users/cm94evuqx0002legvvcg0fxa3

###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
  "title": "My second post",
  "content": "This is the content of my second post",
  "published": false
}

###
GET http://localhost:3000/posts
Authorization: Bearer {{tokenAdmin}}

###
GET http://localhost:3000/posts/cm94zss9s0001legoe5ky1uxf
Authorization: Bearer {{tokenReader}}

###
PATCH http://localhost:3000/posts/cm94zss9s0001legoe5ky1uxf
Content-Type: application/json
Authorization: Bearer {{tokenReader}}

{
  "published": true
}