services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
